In [1]:
import pandas as pd
import numpy as np

In [2]:
weights = []

for i in range(0,22):
    weights.append(pd.read_csv(f'~/Torkamani_Projects/20210712_Analysis-RegeniePaper/CAD_PRS/SBayesR/exBTs_regenie_phenoCol1_SPA_CADComp.regenie.chr{i+1}.reweighted.snpRes',sep='\s+',engine='python'))
    weights[i] = weights[i][['Chrom','Position','A1','A2','A1Effect']]
    weights[i] = weights[i].rename(columns={'Chrom': 'chr', 'Position': 'bp', 'A1':'non_effect_allele', 'A2':'effect_allele', 'A1Effect':'weight'})

In [3]:
weights[0]

        chr         bp effect_allele non_effect_allele    weight
0         1     717587             G                 A  0.000007
1         1     757640             G                 A -0.000018
2         1     761732             C                 T -0.000028
3         1     768448             G                 A -0.000009
4         1     777232             C                 T -0.000029
...     ...        ...           ...               ...       ...
213109    1  249179856             T                 C -0.000086
213110    1  249180765             G                 A -0.000120
213111    1  249181149             A                 G  0.000066
213112    1  249182887             T                 C -0.000037
213113    1  249183206             A                 G -0.000064

[213114 rows x 5 columns]

In [4]:
for i in range(0,22):
    subdata = weights[i].loc[weights[i]['weight'] < 0]
    subdata = pd.DataFrame({
        'chr':subdata['chr'],
        'bp':subdata['bp'],
        'effect_allele':subdata['non_effect_allele'],\
        'non_effect_allele':subdata['effect_allele'],
        'weight':(subdata['weight']*-1)
    })
    weights[i].update(subdata)
    weights[i] = weights[i].astype({'chr': int, 'bp':int})

In [5]:
weights[0]

        chr         bp effect_allele non_effect_allele    weight
0         1     717587             G                 A  0.000007
1         1     757640             A                 G  0.000018
2         1     761732             T                 C  0.000028
3         1     768448             A                 G  0.000009
4         1     777232             T                 C  0.000029
...     ...        ...           ...               ...       ...
213109    1  249179856             C                 T  0.000086
213110    1  249180765             A                 G  0.000120
213111    1  249181149             A                 G  0.000066
213112    1  249182887             C                 T  0.000037
213113    1  249183206             G                 A  0.000064

[213114 rows x 5 columns]

In [6]:
output = weights[0].append(weights[1:])

In [7]:
output

       chr        bp effect_allele non_effect_allele    weight
0        1    717587             G                 A  0.000007
1        1    757640             A                 G  0.000018
2        1    761732             T                 C  0.000028
3        1    768448             A                 G  0.000009
4        1    777232             T                 C  0.000029
...    ...       ...           ...               ...       ...
42664   22  51198569             G                 C  0.000031
42665   22  51198906             G                 A  0.000071
42666   22  51211031             G                 A  0.000004
42667   22  51213613             T                 C  0.000012
42668   22  51217954             A                 G  0.000031

[2865114 rows x 5 columns]

In [11]:
output.to_csv('exBTs_regenie_phenoCol1_SPA_CADComp.regenie.reweighted.csv', index=False)